// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: patientservice/patient.proto

package patientservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetPatientsRequest
type GetPatientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilterName    string                 `protobuf:"bytes,1,opt,name=filter_name,json=filterName,proto3" json:"filter_name,omitempty"`
	FilterEmail   string                 `protobuf:"bytes,2,opt,name=filter_email,json=filterEmail,proto3" json:"filter_email,omitempty"`
	FilterContact string                 `protobuf:"bytes,3,opt,name=filter_contact,json=filterContact,proto3" json:"filter_contact,omitempty"`
	PageNumber    int32                  `protobuf:"varint,4,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize      int32                  `protobuf:"varint,5,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatientsRequest) Reset() {
	*x = GetPatientsRequest{}
	mi := &file_patientservice_patient_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientsRequest) ProtoMessage() {}

func (x *GetPatientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patientservice_patient_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientsRequest.ProtoReflect.Descriptor instead.
func (*GetPatientsRequest) Descriptor() ([]byte, []int) {
	return file_patientservice_patient_proto_rawDescGZIP(), []int{0}
}

func (x *GetPatientsRequest) GetFilterName() string {
	if x != nil {
		return x.FilterName
	}
	return ""
}

func (x *GetPatientsRequest) GetFilterEmail() string {
	if x != nil {
		return x.FilterEmail
	}
	return ""
}

func (x *GetPatientsRequest) GetFilterContact() string {
	if x != nil {
		return x.FilterContact
	}
	return ""
}

func (x *GetPatientsRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *GetPatientsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// GetPatientsResponse
type GetPatientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patients      []*Patient             `protobuf:"bytes,1,rep,name=patients,proto3" json:"patients,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatientsResponse) Reset() {
	*x = GetPatientsResponse{}
	mi := &file_patientservice_patient_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientsResponse) ProtoMessage() {}

func (x *GetPatientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patientservice_patient_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientsResponse.ProtoReflect.Descriptor instead.
func (*GetPatientsResponse) Descriptor() ([]byte, []int) {
	return file_patientservice_patient_proto_rawDescGZIP(), []int{1}
}

func (x *GetPatientsResponse) GetPatients() []*Patient {
	if x != nil {
		return x.Patients
	}
	return nil
}

func (x *GetPatientsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// GetPatientRequest
type GetPatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatientRequest) Reset() {
	*x = GetPatientRequest{}
	mi := &file_patientservice_patient_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientRequest) ProtoMessage() {}

func (x *GetPatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patientservice_patient_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientRequest.ProtoReflect.Descriptor instead.
func (*GetPatientRequest) Descriptor() ([]byte, []int) {
	return file_patientservice_patient_proto_rawDescGZIP(), []int{2}
}

func (x *GetPatientRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

// GetPatientByMedicalIDRequest
type GetPatientByMedicalIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MedicalId     string                 `protobuf:"bytes,1,opt,name=medical_id,json=medicalId,proto3" json:"medical_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatientByMedicalIDRequest) Reset() {
	*x = GetPatientByMedicalIDRequest{}
	mi := &file_patientservice_patient_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatientByMedicalIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientByMedicalIDRequest) ProtoMessage() {}

func (x *GetPatientByMedicalIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patientservice_patient_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientByMedicalIDRequest.ProtoReflect.Descriptor instead.
func (*GetPatientByMedicalIDRequest) Descriptor() ([]byte, []int) {
	return file_patientservice_patient_proto_rawDescGZIP(), []int{3}
}

func (x *GetPatientByMedicalIDRequest) GetMedicalId() string {
	if x != nil {
		return x.MedicalId
	}
	return ""
}

// GetPatientResponse
type GetPatientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patient       *Patient               `protobuf:"bytes,1,opt,name=patient,proto3" json:"patient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatientResponse) Reset() {
	*x = GetPatientResponse{}
	mi := &file_patientservice_patient_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatientResponse) ProtoMessage() {}

func (x *GetPatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patientservice_patient_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatientResponse.ProtoReflect.Descriptor instead.
func (*GetPatientResponse) Descriptor() ([]byte, []int) {
	return file_patientservice_patient_proto_rawDescGZIP(), []int{4}
}

func (x *GetPatientResponse) GetPatient() *Patient {
	if x != nil {
		return x.Patient
	}
	return nil
}

// CreatePatientRequest
type CreatePatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patient       *Patient               `protobuf:"bytes,1,opt,name=patient,proto3" json:"patient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePatientRequest) Reset() {
	*x = CreatePatientRequest{}
	mi := &file_patientservice_patient_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePatientRequest) ProtoMessage() {}

func (x *CreatePatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patientservice_patient_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePatientRequest.ProtoReflect.Descriptor instead.
func (*CreatePatientRequest) Descriptor() ([]byte, []int) {
	return file_patientservice_patient_proto_rawDescGZIP(), []int{5}
}

func (x *CreatePatientRequest) GetPatient() *Patient {
	if x != nil {
		return x.Patient
	}
	return nil
}

// CreatePatientResponse
type CreatePatientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patient       *Patient               `protobuf:"bytes,1,opt,name=patient,proto3" json:"patient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePatientResponse) Reset() {
	*x = CreatePatientResponse{}
	mi := &file_patientservice_patient_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePatientResponse) ProtoMessage() {}

func (x *CreatePatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patientservice_patient_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePatientResponse.ProtoReflect.Descriptor instead.
func (*CreatePatientResponse) Descriptor() ([]byte, []int) {
	return file_patientservice_patient_proto_rawDescGZIP(), []int{6}
}

func (x *CreatePatientResponse) GetPatient() *Patient {
	if x != nil {
		return x.Patient
	}
	return nil
}

// UpdatePatientRequest
type UpdatePatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	Patient       *Patient               `protobuf:"bytes,2,opt,name=patient,proto3" json:"patient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePatientRequest) Reset() {
	*x = UpdatePatientRequest{}
	mi := &file_patientservice_patient_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePatientRequest) ProtoMessage() {}

func (x *UpdatePatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patientservice_patient_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePatientRequest.ProtoReflect.Descriptor instead.
func (*UpdatePatientRequest) Descriptor() ([]byte, []int) {
	return file_patientservice_patient_proto_rawDescGZIP(), []int{7}
}

func (x *UpdatePatientRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *UpdatePatientRequest) GetPatient() *Patient {
	if x != nil {
		return x.Patient
	}
	return nil
}

// UpdatePatientResponse
type UpdatePatientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patient       *Patient               `protobuf:"bytes,1,opt,name=patient,proto3" json:"patient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePatientResponse) Reset() {
	*x = UpdatePatientResponse{}
	mi := &file_patientservice_patient_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePatientResponse) ProtoMessage() {}

func (x *UpdatePatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patientservice_patient_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePatientResponse.ProtoReflect.Descriptor instead.
func (*UpdatePatientResponse) Descriptor() ([]byte, []int) {
	return file_patientservice_patient_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePatientResponse) GetPatient() *Patient {
	if x != nil {
		return x.Patient
	}
	return nil
}

// DeletePatientRequest
type DeletePatientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePatientRequest) Reset() {
	*x = DeletePatientRequest{}
	mi := &file_patientservice_patient_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePatientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePatientRequest) ProtoMessage() {}

func (x *DeletePatientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_patientservice_patient_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePatientRequest.ProtoReflect.Descriptor instead.
func (*DeletePatientRequest) Descriptor() ([]byte, []int) {
	return file_patientservice_patient_proto_rawDescGZIP(), []int{9}
}

func (x *DeletePatientRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

// DeletePatientResponse
type DeletePatientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePatientResponse) Reset() {
	*x = DeletePatientResponse{}
	mi := &file_patientservice_patient_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePatientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePatientResponse) ProtoMessage() {}

func (x *DeletePatientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_patientservice_patient_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePatientResponse.ProtoReflect.Descriptor instead.
func (*DeletePatientResponse) Descriptor() ([]byte, []int) {
	return file_patientservice_patient_proto_rawDescGZIP(), []int{10}
}

func (x *DeletePatientResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Patient
type Patient struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId            string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name              string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	DateOfBirth       string                 `protobuf:"bytes,4,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Age               int32                  `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	Gender            string                 `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Contact           string                 `protobuf:"bytes,7,opt,name=contact,proto3" json:"contact,omitempty"`
	MedicalId         string                 `protobuf:"bytes,8,opt,name=medical_id,json=medicalId,proto3" json:"medical_id,omitempty"`
	Nationality       string                 `protobuf:"bytes,9,opt,name=nationality,proto3" json:"nationality,omitempty"`
	Email             string                 `protobuf:"bytes,10,opt,name=email,proto3" json:"email,omitempty"`
	Languages         []string               `protobuf:"bytes,11,rep,name=languages,proto3" json:"languages,omitempty"`
	EmergencyContacts []*EmergencyContact    `protobuf:"bytes,12,rep,name=emergency_contacts,json=emergencyContacts,proto3" json:"emergency_contacts,omitempty"`
	Diagnoses         []*Diagnosis           `protobuf:"bytes,13,rep,name=diagnoses,proto3" json:"diagnoses,omitempty"`
	Address           *Address               `protobuf:"bytes,14,opt,name=address,proto3" json:"address,omitempty"`
	CreatedAt         string                 `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         string                 `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Patient) Reset() {
	*x = Patient{}
	mi := &file_patientservice_patient_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Patient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Patient) ProtoMessage() {}

func (x *Patient) ProtoReflect() protoreflect.Message {
	mi := &file_patientservice_patient_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Patient.ProtoReflect.Descriptor instead.
func (*Patient) Descriptor() ([]byte, []int) {
	return file_patientservice_patient_proto_rawDescGZIP(), []int{11}
}

func (x *Patient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Patient) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Patient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Patient) GetDateOfBirth() string {
	if x != nil {
		return x.DateOfBirth
	}
	return ""
}

func (x *Patient) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *Patient) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Patient) GetContact() string {
	if x != nil {
		return x.Contact
	}
	return ""
}

func (x *Patient) GetMedicalId() string {
	if x != nil {
		return x.MedicalId
	}
	return ""
}

func (x *Patient) GetNationality() string {
	if x != nil {
		return x.Nationality
	}
	return ""
}

func (x *Patient) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Patient) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *Patient) GetEmergencyContacts() []*EmergencyContact {
	if x != nil {
		return x.EmergencyContacts
	}
	return nil
}

func (x *Patient) GetDiagnoses() []*Diagnosis {
	if x != nil {
		return x.Diagnoses
	}
	return nil
}

func (x *Patient) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Patient) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Patient) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// EmergencyContact
type EmergencyContact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Relationship  string                 `protobuf:"bytes,2,opt,name=relationship,proto3" json:"relationship,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmergencyContact) Reset() {
	*x = EmergencyContact{}
	mi := &file_patientservice_patient_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmergencyContact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmergencyContact) ProtoMessage() {}

func (x *EmergencyContact) ProtoReflect() protoreflect.Message {
	mi := &file_patientservice_patient_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmergencyContact.ProtoReflect.Descriptor instead.
func (*EmergencyContact) Descriptor() ([]byte, []int) {
	return file_patientservice_patient_proto_rawDescGZIP(), []int{12}
}

func (x *EmergencyContact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EmergencyContact) GetRelationship() string {
	if x != nil {
		return x.Relationship
	}
	return ""
}

func (x *EmergencyContact) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

// Diagnosis
type Diagnosis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Condition     string                 `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diagnosis) Reset() {
	*x = Diagnosis{}
	mi := &file_patientservice_patient_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnosis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnosis) ProtoMessage() {}

func (x *Diagnosis) ProtoReflect() protoreflect.Message {
	mi := &file_patientservice_patient_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnosis.ProtoReflect.Descriptor instead.
func (*Diagnosis) Descriptor() ([]byte, []int) {
	return file_patientservice_patient_proto_rawDescGZIP(), []int{13}
}

func (x *Diagnosis) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *Diagnosis) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

// Address
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Zip           string                 `protobuf:"bytes,4,opt,name=zip,proto3" json:"zip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_patientservice_patient_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_patientservice_patient_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_patientservice_patient_proto_rawDescGZIP(), []int{14}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetZip() string {
	if x != nil {
		return x.Zip
	}
	return ""
}

var File_patientservice_patient_proto protoreflect.FileDescriptor

const file_patientservice_patient_proto_rawDesc = "" +
	"\n" +
	"\x1cpatientservice/patient.proto\x12\x0epatientservice\"\xbd\x01\n" +
	"\x12GetPatientsRequest\x12\x1f\n" +
	"\vfilter_name\x18\x01 \x01(\tR\n" +
	"filterName\x12!\n" +
	"\ffilter_email\x18\x02 \x01(\tR\vfilterEmail\x12%\n" +
	"\x0efilter_contact\x18\x03 \x01(\tR\rfilterContact\x12\x1f\n" +
	"\vpage_number\x18\x04 \x01(\x05R\n" +
	"pageNumber\x12\x1b\n" +
	"\tpage_size\x18\x05 \x01(\x05R\bpageSize\"k\n" +
	"\x13GetPatientsResponse\x123\n" +
	"\bpatients\x18\x01 \x03(\v2\x17.patientservice.PatientR\bpatients\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"2\n" +
	"\x11GetPatientRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\"=\n" +
	"\x1cGetPatientByMedicalIDRequest\x12\x1d\n" +
	"\n" +
	"medical_id\x18\x01 \x01(\tR\tmedicalId\"G\n" +
	"\x12GetPatientResponse\x121\n" +
	"\apatient\x18\x01 \x01(\v2\x17.patientservice.PatientR\apatient\"I\n" +
	"\x14CreatePatientRequest\x121\n" +
	"\apatient\x18\x01 \x01(\v2\x17.patientservice.PatientR\apatient\"J\n" +
	"\x15CreatePatientResponse\x121\n" +
	"\apatient\x18\x01 \x01(\v2\x17.patientservice.PatientR\apatient\"h\n" +
	"\x14UpdatePatientRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x121\n" +
	"\apatient\x18\x02 \x01(\v2\x17.patientservice.PatientR\apatient\"J\n" +
	"\x15UpdatePatientResponse\x121\n" +
	"\apatient\x18\x01 \x01(\v2\x17.patientservice.PatientR\apatient\"5\n" +
	"\x14DeletePatientRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\"1\n" +
	"\x15DeletePatientResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x9e\x04\n" +
	"\aPatient\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\"\n" +
	"\rdate_of_birth\x18\x04 \x01(\tR\vdateOfBirth\x12\x10\n" +
	"\x03age\x18\x05 \x01(\x05R\x03age\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\tR\x06gender\x12\x18\n" +
	"\acontact\x18\a \x01(\tR\acontact\x12\x1d\n" +
	"\n" +
	"medical_id\x18\b \x01(\tR\tmedicalId\x12 \n" +
	"\vnationality\x18\t \x01(\tR\vnationality\x12\x14\n" +
	"\x05email\x18\n" +
	" \x01(\tR\x05email\x12\x1c\n" +
	"\tlanguages\x18\v \x03(\tR\tlanguages\x12O\n" +
	"\x12emergency_contacts\x18\f \x03(\v2 .patientservice.EmergencyContactR\x11emergencyContacts\x127\n" +
	"\tdiagnoses\x18\r \x03(\v2\x19.patientservice.DiagnosisR\tdiagnoses\x121\n" +
	"\aaddress\x18\x0e \x01(\v2\x17.patientservice.AddressR\aaddress\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\tR\tupdatedAt\"`\n" +
	"\x10EmergencyContact\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\"\n" +
	"\frelationship\x18\x02 \x01(\tR\frelationship\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\"=\n" +
	"\tDiagnosis\x12\x1c\n" +
	"\tcondition\x18\x01 \x01(\tR\tcondition\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\"]\n" +
	"\aAddress\x12\x16\n" +
	"\x06street\x18\x01 \x01(\tR\x06street\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x10\n" +
	"\x03zip\x18\x04 \x01(\tR\x03zip2\xc2\x04\n" +
	"\x0ePatientService\x12V\n" +
	"\vGetPatients\x12\".patientservice.GetPatientsRequest\x1a#.patientservice.GetPatientsResponse\x12S\n" +
	"\n" +
	"GetPatient\x12!.patientservice.GetPatientRequest\x1a\".patientservice.GetPatientResponse\x12i\n" +
	"\x15GetPatientByMedicalID\x12,.patientservice.GetPatientByMedicalIDRequest\x1a\".patientservice.GetPatientResponse\x12\\\n" +
	"\rCreatePatient\x12$.patientservice.CreatePatientRequest\x1a%.patientservice.CreatePatientResponse\x12\\\n" +
	"\rUpdatePatient\x12$.patientservice.UpdatePatientRequest\x1a%.patientservice.UpdatePatientResponse\x12\\\n" +
	"\rDeletePatient\x12$.patientservice.DeletePatientRequest\x1a%.patientservice.DeletePatientResponseB!Z\x1f./patientservice;patientserviceb\x06proto3"

var (
	file_patientservice_patient_proto_rawDescOnce sync.Once
	file_patientservice_patient_proto_rawDescData []byte
)

func file_patientservice_patient_proto_rawDescGZIP() []byte {
	file_patientservice_patient_proto_rawDescOnce.Do(func() {
		file_patientservice_patient_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_patientservice_patient_proto_rawDesc), len(file_patientservice_patient_proto_rawDesc)))
	})
	return file_patientservice_patient_proto_rawDescData
}

var file_patientservice_patient_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_patientservice_patient_proto_goTypes = []any{
	(*GetPatientsRequest)(nil),           // 0: patientservice.GetPatientsRequest
	(*GetPatientsResponse)(nil),          // 1: patientservice.GetPatientsResponse
	(*GetPatientRequest)(nil),            // 2: patientservice.GetPatientRequest
	(*GetPatientByMedicalIDRequest)(nil), // 3: patientservice.GetPatientByMedicalIDRequest
	(*GetPatientResponse)(nil),           // 4: patientservice.GetPatientResponse
	(*CreatePatientRequest)(nil),         // 5: patientservice.CreatePatientRequest
	(*CreatePatientResponse)(nil),        // 6: patientservice.CreatePatientResponse
	(*UpdatePatientRequest)(nil),         // 7: patientservice.UpdatePatientRequest
	(*UpdatePatientResponse)(nil),        // 8: patientservice.UpdatePatientResponse
	(*DeletePatientRequest)(nil),         // 9: patientservice.DeletePatientRequest
	(*DeletePatientResponse)(nil),        // 10: patientservice.DeletePatientResponse
	(*Patient)(nil),                      // 11: patientservice.Patient
	(*EmergencyContact)(nil),             // 12: patientservice.EmergencyContact
	(*Diagnosis)(nil),                    // 13: patientservice.Diagnosis
	(*Address)(nil),                      // 14: patientservice.Address
}
var file_patientservice_patient_proto_depIdxs = []int32{
	11, // 0: patientservice.GetPatientsResponse.patients:type_name -> patientservice.Patient
	11, // 1: patientservice.GetPatientResponse.patient:type_name -> patientservice.Patient
	11, // 2: patientservice.CreatePatientRequest.patient:type_name -> patientservice.Patient
	11, // 3: patientservice.CreatePatientResponse.patient:type_name -> patientservice.Patient
	11, // 4: patientservice.UpdatePatientRequest.patient:type_name -> patientservice.Patient
	11, // 5: patientservice.UpdatePatientResponse.patient:type_name -> patientservice.Patient
	12, // 6: patientservice.Patient.emergency_contacts:type_name -> patientservice.EmergencyContact
	13, // 7: patientservice.Patient.diagnoses:type_name -> patientservice.Diagnosis
	14, // 8: patientservice.Patient.address:type_name -> patientservice.Address
	0,  // 9: patientservice.PatientService.GetPatients:input_type -> patientservice.GetPatientsRequest
	2,  // 10: patientservice.PatientService.GetPatient:input_type -> patientservice.GetPatientRequest
	3,  // 11: patientservice.PatientService.GetPatientByMedicalID:input_type -> patientservice.GetPatientByMedicalIDRequest
	5,  // 12: patientservice.PatientService.CreatePatient:input_type -> patientservice.CreatePatientRequest
	7,  // 13: patientservice.PatientService.UpdatePatient:input_type -> patientservice.UpdatePatientRequest
	9,  // 14: patientservice.PatientService.DeletePatient:input_type -> patientservice.DeletePatientRequest
	1,  // 15: patientservice.PatientService.GetPatients:output_type -> patientservice.GetPatientsResponse
	4,  // 16: patientservice.PatientService.GetPatient:output_type -> patientservice.GetPatientResponse
	4,  // 17: patientservice.PatientService.GetPatientByMedicalID:output_type -> patientservice.GetPatientResponse
	6,  // 18: patientservice.PatientService.CreatePatient:output_type -> patientservice.CreatePatientResponse
	8,  // 19: patientservice.PatientService.UpdatePatient:output_type -> patientservice.UpdatePatientResponse
	10, // 20: patientservice.PatientService.DeletePatient:output_type -> patientservice.DeletePatientResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_patientservice_patient_proto_init() }
func file_patientservice_patient_proto_init() {
	if File_patientservice_patient_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_patientservice_patient_proto_rawDesc), len(file_patientservice_patient_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_patientservice_patient_proto_goTypes,
		DependencyIndexes: file_patientservice_patient_proto_depIdxs,
		MessageInfos:      file_patientservice_patient_proto_msgTypes,
	}.Build()
	File_patientservice_patient_proto = out.File
	file_patientservice_patient_proto_goTypes = nil
	file_patientservice_patient_proto_depIdxs = nil
}
