// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: gateway/registration.proto

package apigateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	GrpcEndpoint  string                 `protobuf:"bytes,2,opt,name=grpc_endpoint,json=grpcEndpoint,proto3" json:"grpc_endpoint,omitempty"`
	HttpEndpoint  string                 `protobuf:"bytes,3,opt,name=http_endpoint,json=httpEndpoint,proto3" json:"http_endpoint,omitempty"`
	Methods       []string               `protobuf:"bytes,4,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRegistrationRequest) Reset() {
	*x = ServiceRegistrationRequest{}
	mi := &file_gateway_registration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRegistrationRequest) ProtoMessage() {}

func (x *ServiceRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_registration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRegistrationRequest.ProtoReflect.Descriptor instead.
func (*ServiceRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_gateway_registration_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceRegistrationRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceRegistrationRequest) GetGrpcEndpoint() string {
	if x != nil {
		return x.GrpcEndpoint
	}
	return ""
}

func (x *ServiceRegistrationRequest) GetHttpEndpoint() string {
	if x != nil {
		return x.HttpEndpoint
	}
	return ""
}

func (x *ServiceRegistrationRequest) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

type ServiceRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceRegistrationResponse) Reset() {
	*x = ServiceRegistrationResponse{}
	mi := &file_gateway_registration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceRegistrationResponse) ProtoMessage() {}

func (x *ServiceRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_registration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceRegistrationResponse.ProtoReflect.Descriptor instead.
func (*ServiceRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_gateway_registration_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceRegistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ServiceRegistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ServiceDeregistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDeregistrationRequest) Reset() {
	*x = ServiceDeregistrationRequest{}
	mi := &file_gateway_registration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDeregistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDeregistrationRequest) ProtoMessage() {}

func (x *ServiceDeregistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_registration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDeregistrationRequest.ProtoReflect.Descriptor instead.
func (*ServiceDeregistrationRequest) Descriptor() ([]byte, []int) {
	return file_gateway_registration_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceDeregistrationRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type ServiceDeregistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDeregistrationResponse) Reset() {
	*x = ServiceDeregistrationResponse{}
	mi := &file_gateway_registration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDeregistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDeregistrationResponse) ProtoMessage() {}

func (x *ServiceDeregistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_registration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDeregistrationResponse.ProtoReflect.Descriptor instead.
func (*ServiceDeregistrationResponse) Descriptor() ([]byte, []int) {
	return file_gateway_registration_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceDeregistrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ServiceDeregistrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_gateway_registration_proto protoreflect.FileDescriptor

const file_gateway_registration_proto_rawDesc = "" +
	"\n" +
	"\x1agateway/registration.proto\x12\fauditlogging\"\xa3\x01\n" +
	"\x1aServiceRegistrationRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12#\n" +
	"\rgrpc_endpoint\x18\x02 \x01(\tR\fgrpcEndpoint\x12#\n" +
	"\rhttp_endpoint\x18\x03 \x01(\tR\fhttpEndpoint\x12\x18\n" +
	"\amethods\x18\x04 \x03(\tR\amethods\"Q\n" +
	"\x1bServiceRegistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"A\n" +
	"\x1cServiceDeregistrationRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"S\n" +
	"\x1dServiceDeregistrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xd9\x01\n" +
	"\x0fServiceRegistry\x12_\n" +
	"\bRegister\x12(.auditlogging.ServiceRegistrationRequest\x1a).auditlogging.ServiceRegistrationResponse\x12e\n" +
	"\n" +
	"Deregister\x12*.auditlogging.ServiceDeregistrationRequest\x1a+.auditlogging.ServiceDeregistrationResponseB\x19Z\x17./apigateway;apigatewayb\x06proto3"

var (
	file_gateway_registration_proto_rawDescOnce sync.Once
	file_gateway_registration_proto_rawDescData []byte
)

func file_gateway_registration_proto_rawDescGZIP() []byte {
	file_gateway_registration_proto_rawDescOnce.Do(func() {
		file_gateway_registration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_registration_proto_rawDesc), len(file_gateway_registration_proto_rawDesc)))
	})
	return file_gateway_registration_proto_rawDescData
}

var file_gateway_registration_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_gateway_registration_proto_goTypes = []any{
	(*ServiceRegistrationRequest)(nil),    // 0: auditlogging.ServiceRegistrationRequest
	(*ServiceRegistrationResponse)(nil),   // 1: auditlogging.ServiceRegistrationResponse
	(*ServiceDeregistrationRequest)(nil),  // 2: auditlogging.ServiceDeregistrationRequest
	(*ServiceDeregistrationResponse)(nil), // 3: auditlogging.ServiceDeregistrationResponse
}
var file_gateway_registration_proto_depIdxs = []int32{
	0, // 0: auditlogging.ServiceRegistry.Register:input_type -> auditlogging.ServiceRegistrationRequest
	2, // 1: auditlogging.ServiceRegistry.Deregister:input_type -> auditlogging.ServiceDeregistrationRequest
	1, // 2: auditlogging.ServiceRegistry.Register:output_type -> auditlogging.ServiceRegistrationResponse
	3, // 3: auditlogging.ServiceRegistry.Deregister:output_type -> auditlogging.ServiceDeregistrationResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gateway_registration_proto_init() }
func file_gateway_registration_proto_init() {
	if File_gateway_registration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_registration_proto_rawDesc), len(file_gateway_registration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_registration_proto_goTypes,
		DependencyIndexes: file_gateway_registration_proto_depIdxs,
		MessageInfos:      file_gateway_registration_proto_msgTypes,
	}.Build()
	File_gateway_registration_proto = out.File
	file_gateway_registration_proto_goTypes = nil
	file_gateway_registration_proto_depIdxs = nil
}
